# Generated by Django 4.1.7 on 2023-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employees_delete_partydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('party_date', models.DateField()),
                ('suppliers_date', models.DateField()),
                ('guest_count', models.IntegerField()),
                ('party_type', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('theme', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
