# Generated by Django 4.1.7 on 2023-08-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_partydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partydetails',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='partydetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partydetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='partydetails',
            name='party_date',
        ),
        migrations.RemoveField(
            model_name='partydetails',
            name='party_type',
        ),
        migrations.RemoveField(
            model_name='partydetails',
            name='suppliers_date',
        ),
        migrations.RemoveField(
            model_name='partydetails',
            name='theme',
        ),
    ]
